feat: adds @Decorator related sorting rules
azat-io/eslint-plugin-perfectionist pull request #304
Opened 2024-10-05 16:13 UTC by hugop95

### Description

A rule to sort decorators exists here: https://github.com/ElsiKora/ESLint-Plugin-Sort-Decorators.

However, it doesn't benefit from the `eslint-plugin-perfectionist` options ecosystem (possibility to group elements, add custom groups, partition by comment, etc.).

Decorators order may sometimes matter, so giving users the option to keep that order in those cases is necessary.

Additionally, this implementation has some differences related to what we consider an `accessor decorator` (explained below). 

## Changes

This PR adds 4 new decorator-related rules:
- `sort-class-decorators`
- `sort-property-decorators`
- `sort-method-decorators`
- `sort-parameter-decorators`
- `sort-accessor-decorators`

### Options

All these rules have the **same** options: their logic is exactly the same, but applied on different elements.

- `type`
- `order`
- `ignoreCase`
- `groups`
- `customGroups`
- `partitionByComment`
- `matcher`

`partitionByNewLine` was not added as I don't think there is a use case in separating decorators with a new line. This can be  easily added if necessary.

There is at the moment only one predefined group: `unknown`.

### `sort-accessor-decorators`

Works on **auto-accessors**, not getters. Getters/setters are affected by `sort-method-decorators`.

## ⚠️ Should this be included in recommended configs?

Decorators are evaluated from top to bottom. Activating these rules without proper configuration **CAN** cause runtime errors. While unusual, decorator order may matter in some projects.

At the moment, there are 2 other rules that may change behavior unexpectedly through sorting and that are present in recommended configs:
- `sort-maps`
- `sort-sets`

(If users depend on insertion order, although it is unusual).

I think that if we choose not to include this rule into `recommended`, then both of the above rules should not be included as well.

### What is the purpose of this pull request? 

- [x] New Feature
- [x] Documentation update

2024-10-06 06:36 UTC, OlivierZal commented on rules/sort-class-decorators.ts
> +    .map(nodes => sortNodesByGroups(nodes, options))
`.flatMap()` ?

2024-10-06 07:59 UTC, OlivierZal commented
Couldn't there be a conflict of precedence (at least from the user point of view) with `decoratorNamePattern` defined under `sort-classes`.`customGroups`?

Maybe something to pay attention in `sort-classes` and `sort-xxx-decorators`.

2024-10-06 10:42 UTC, hugop95 commented on rules/sort-class-decorators.ts
> +    .map(nodes => sortNodesByGroups(nodes, options))
Thanks, I keep forgetting about that 😄

2024-10-06 10:44 UTC, hugop95 commented
> Couldn't there be a conflict of precedence (at least from the user point of view) with `sort-classes`.`customGroups` relying on a `decoratorNamePattern`?
> 
> Maybe something to pay attention in `sort-classes` and `sort-xxx-decorators` documentations.
> 
> By the way I ❤️ these new rule proposals.

@OlivierZal This is fine: in `sort-classes`, `decoratorNamePattern` is used to target class members that have at least one decorator with the entered pattern. The order of decorators does not matter.

2024-10-06 11:44 UTC, OlivierZal commented
Got it. 

Then config is important because unlike class members, order matters – like it matters for arrays, because decorators apply sequentially.

2024-10-06 13:01 UTC, hugop95 commented
> Got it. 
> 
> Then config is important because unlike class members, order matters – like it matters for arrays, because decorators apply sequentially. 

Yes, I mention it at the bottom of the PR, regarding whether the rules should be in recommended configs.

2024-10-06 21:46 UTC, OlivierZal commented
@hugop95, I know it's a draft. I've read your current tests: I've not found the other decorator syntaxes:

```ts
@a @b
something
```

and

```ts
@a @b something
```

Doesn't it worth to test them? Do you want to allow keeping the original syntax as an option? (not necessarily in the first version of these rules).

2024-10-06 23:25 UTC, hugop95 commented
@OlivierZal 
This implementation will not affect elements style-wise: decorators are permuted, so no whitespace/newline is added/removed.

However, it can still be interesting to ensure that this does not get broken, so I'll just edit a couple of tests to have an inline syntax and this should be enough.

2024-10-07 19:00 UTC, OlivierZal commented on docs/content/rules/sort-accessor-decorators.mdx
> +description: Enforce sorting of accessor decorators for for improved readability and maintainability. Use this ESLint rule to keep your accessor decorators well-organized
`for for`

2024-10-09 06:19 UTC, hugop95 commented
@azat-io 

Should we include this in recommended configs?

Decorators are evaluated from top to bottom. While unusual, decorator order may matter in some projects. Activating these rules without proper configuration **CAN** cause runtime errors.

At the moment, there are 2 other rules that may change behavior unexpectedly through sorting and that are present in recommended configs:
- `sort-maps`
- `sort-sets`

(If users depend on insertion order, although it is unusual).

I think that if we choose not to include this rule into `recommended`, then both of the above rules should not be included as well.

2024-10-09 16:59 UTC, azat-io requested changes
Thank you for your contributions!

I think it would be better to combine all these rules into one `sort-decorators` rule?

I think most of the time people don't want to configure each rule separately and for decorators it makes sense to combine everything.

2024-10-09 17:27 UTC, azat-io commented
Other than that, I like everything. It's a very cool idea. But it would be nice to combine these rules into one.

2024-10-09 18:06 UTC, hugop95 commented
Alright, I'll regroup that in one rule and add options to enable/disable it on `methods`, `classes` etc.

2024-10-10 07:39 UTC, OlivierZal approved these changes
All good for me @hugop95, great work!

2024-10-10 10:01 UTC, azat-io reviewed
@hugop95 Looks good, awesome work!

1. Could you please also combine test files into one?
2. And we need to add new rule to rule list in `readme.md`

2024-10-12 09:30 UTC, hugop95 commented
@azat-io Done. Do you think we should release this in a new major version (v4.0.0)? We could add some breaking changes as well in it:

- https://github.com/azat-io/eslint-plugin-perfectionist/issues/309
- Maybe remove the old `customGroups` API in `sort-custom-classes` ?

2024-10-12 12:08 UTC, OlivierZal approved these changes

2024-10-15 09:42 UTC, azat-io commented
@hugop95 Okay, let's do it in the major version. We'll just have to think about the plan for this release and think about what other changes we want to have.

2024-10-15 16:21 UTC, azat-io commented
I have created a `next` branch, could you please direct your pull request to this branch?

2024-10-15 18:22 UTC, hugop95 commented
@azat-io Done!

2024-10-17 21:56 UTC, merged

2024-10-17 21:56 UTC, azat-io commented
Awesome, thank you!

2024-10-17 22:11 UTC, OlivierZal commented
Great achievement @hugop95!

2024-10-17 22:21 UTC, hugop95 commented
> Great achievement @hugop95!

Thank you for the feedback ! Always appreciated.