feat(sort-enums): handles numeric operations
azat-io/eslint-plugin-perfectionist pull request #387
Opened 2024-11-20 09:10 UTC by hugop95

Fixes #386

### Description

Today, users have the possibility to sort numeric enums. However, numeric enums might not directly be written with literal numeric values.

```ts
enum Enum {
  A = 60
  B = 60 * 60 * 24 * 31 // About 1 month in seconds 
}
``` 

This PR handles numeric operations on enum values to deduce its number, and sort them appropriately.

### What is the purpose of this pull request? 

- [x] Bug fix
- [x] New Feature

2024-11-20 11:40 UTC, OlivierZal commented
That's not the topic, but I was wondering when reading your PR whether a `sort-operators` would be use useful, but I guess not since the operator ordering often reflects a logic that a rule cannot catch...

2024-11-20 12:37 UTC, OlivierZal commented
@hugop95, looks good to me, I've just added a small comment.

That's not the topic, but I was wondering when reading your PR whether a sort-operators would be use useful, but I guess not since the operator ordering (with its members) often reflects a logic that a systematic rule cannot catch...

2024-11-20 12:53 UTC, hugop95 commented on rules/sort-enums.ts
> +    default:
@OlivierZal Good idea!

2024-11-20 13:09 UTC, hugop95 commented
@OlivierZal 

> That's not the topic, but I was wondering when reading your PR whether a sort-operators would be use useful, but I guess not since the operator ordering (with its members) often reflects a logic that a systematic rule cannot catch...

I don't think users are actively looking to order operation members in an alphabetical/numerical way. Logic readability is more important as you say.

2024-11-21 09:17 UTC, hugop95 commented on rules/sort-enums.ts
> +    default:
@OlivierZal Operators added: `>>`, `<<`, `|`, `&`.

2024-11-21 12:29 UTC, OlivierZal requested changes

2024-11-21 12:29 UTC, OlivierZal commented on rules/sort-enums.ts
> +      return left | right
&

2024-11-21 12:35 UTC, hugop95 commented on rules/sort-enums.ts
> +      return left | right
Oops! Fixed. fa41159387aa605412d9cac43c96fa00b6abc248

2024-11-21 13:11 UTC, OlivierZal commented on rules/sort-enums.ts
> +    default:
Great! And what about the following? `^` (XOR), `~^` / `^~` (XNOR)

2024-11-21 20:27 UTC, hugop95 commented on rules/sort-enums.ts
> +    default:
@OlivierZal `^` added in 75df1b1d6808d7445684b980958ddcae4dbc5ab9. `^~` is handled through `^` and `~` directly.

2024-11-21 23:21 UTC, azat-io approved these changes

2024-11-21 23:21 UTC, merged

2024-11-21 23:21 UTC, azat-io commented
Thanks!